version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: geo-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "1071:3306"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: geo-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: geo-webserver
      working_dir: /application
      env_file:
        - .env
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: geo-php-fpm
      working_dir: /application
      env_file:
        - .env
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8080:80'
      environment:
        - PMA_HOST=mysql
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
